<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login CBT</title>

    {{-- Load Tailwind via Vite --}}
    @vite('resources/css/app.css')
</head>

<body class="bg-gray-100">

    <div class="flex items-center justify-center min-h-screen">

        <div class="bg-white shadow-lg rounded-lg p-8 w-full max-w-md">

            <h2 class="text-2xl font-bold text-center mb-6 text-gray-700">
                Login CBT SDN Baru 01
            </h2>

            {{-- Error Message --}}
            @if ($errors->any())
                <div class="bg-red-100 text-red-700 px-4 py-2 rounded mb-4">
                    {{ $errors->first() }}
                </div>
            @endif

            {{-- Login Form --}}
            <form action="{{ route('login.post') }}" method="POST">
                @csrf

                <div class="mb-4">
                    <label class="block text-gray-700 mb-1">Username</label>
                    <input type="text" name="username"
                        class="w-full px-3 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
                        required>
                </div>

                {{-- Password + Eye --}}
                <div class="mb-4">
                    <label class="block text-gray-700 mb-1">Password</label>

                    <div class="relative">
                        <input type="password" name="password" id="passwordField"
                            class="w-full px-3 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
                            required>

                        <button type="button" id="togglePassword"
                            class="absolute inset-y-0 right-3 flex items-center text-gray-500">
                            👁️
                        </button>
                    </div>
                </div>

                {{-- Captcha --}}
                <div class="mb-4">
                    <label class="block text-gray-700 mb-1">Kode Keamanan</label>

                    <div class="flex items-center gap-3">
                        <div id="captchaBox"
                             class="px-4 py-2 bg-gray-200 rounded font-bold tracking-widest text-gray-700 select-none">
                            {{-- Captcha generated by JS --}}
                        </div>

                        <button type="button" onclick="generateCaptcha()"
                            class="px-3 py-2 bg-blue-600 text-white rounded hover:bg-blue-700">
                            Refresh
                        </button>
                    </div>

                    <input type="text" name="captcha_input" placeholder="Masukkan kode di atas"
                        class="w-full mt-3 px-3 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
                        required>

                    {{-- hidden input to send captcha value --}}
                    <input type="hidden" name="captcha_real" id="captchaReal">
                </div>

                <button type="submit"
                    class="w-full bg-blue-600 text-white py-2 rounded hover:bg-blue-700 transition">
                    Login
                </button>

            </form>

        </div>

    </div>

    <script>
        // Eye password toggle
        const togglePassword = document.getElementById("togglePassword");
        const passwordField = document.getElementById("passwordField");

        togglePassword.addEventListener("click", () => {
            const type = passwordField.type === "password" ? "text" : "password";
            passwordField.type = type;
            togglePassword.textContent = type === "password" ? "👁️" : "🙈";
        });

        // Simple Captcha Generator
        function generateCaptcha() {
            let chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
            let code = "";
            for (let i = 0; i < 5; i++) {
                code += chars.charAt(Math.floor(Math.random() * chars.length));
            }

            document.getElementById("captchaBox").textContent = code;
            document.getElementById("captchaReal").value = code;
        }

        // Generate captcha on page load
        generateCaptcha();
    </script>

</body>

</html>
